In [1]:
using LinearAlgebra

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %13.3 %                        ]  39.8 % [======================>                  ]  53.1 %66.3 %      ]  84.7 %Fetching: [====================================>    ]  87.8 % Resolving package versions...
 Installed Tables ───────── v0.1.14
 Installed DataStructures ─ v0.15.0
 Installed WebSockets ───── v1.2.0
 Installed GR ───────────── v0.37.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [37e2e46d] + LinearAlgebra 
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [864edb3b] ↑ DataStructures v0.14.0 ⇒ v0.15.0
  [28b8d3ca] ↑ GR v0.36.0 ⇒ v0.37.0
  [bd369af6] ↑ Tables v0.1.12 ⇒ v0.1.14
  [104b5d7c] ↑ WebSockets v1.1.1 ⇒ v1.2.0
  Building GR → `~/.julia/packages/GR/shnUy/deps/build.log`


# Zadanie 1

In [2]:
x = rand(1000)
A = rand(1000,1000)
b = A*x

1000-element Array{Float64,1}:
 255.78968921772434
 255.41703456642927
 252.65287286835806
 248.41294834272497
 258.3106828944218 
 253.0852010441637 
 258.9487224255764 
 249.3841871700951 
 257.1304272093038 
 248.74945627637373
 246.49236697057344
 250.39678608534015
 254.73742757445444
   ⋮               
 249.90893040781444
 239.65270306939604
 250.17673051668189
 251.27103625519499
 247.15759027353454
 249.58977944453773
 240.92796908595338
 249.1406949878608 
 249.50788524154805
 250.54094157131297
 266.4041157670232 
 252.50137621636796

In [19]:
function work(A, b, x, results)
    @time resinv = inv(A)*b
    push!(results, norm(resinv-x))
    @time resslash = A\b
    push!(results, norm(resinv-x))
    @time resfact = factorize(A)\b
    push!(results, norm(resfact-x))
end
results = []
work(A,b,x, results)
results

  0.044230 seconds (5 allocations: 7.645 MiB)
  0.046450 seconds (5 allocations: 7.645 MiB)


3-element Array{Any,1}:
 6.902909569458534e-11
 6.902909569458534e-11
 3.306964327719669e-11

# Zadanie 2

In [21]:
using Plots
using Polynomials
using CSV

┌ Info: Recompiling stale cache file /home/wojlewy/.julia/compiled/v1.0/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1187
┌ Info: Recompiling stale cache file /home/wojlewy/.julia/compiled/v1.0/CSV/HHBkp.ji for CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1187


In [22]:
input ="/home/wojlewy/Pulpit/LewickiWojciech/mownit2/lab10/results.csv"
results =CSV.read(input, delim=";")

10×15 DataFrames.DataFrame. Omitted printing of 9 columns
│ Row │ naive100 │ naive200 │ naive300 │ naive400 │ naive500 │ better100 │
│     │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰ │ Float64⍰  │
├─────┼──────────┼──────────┼──────────┼──────────┼──────────┼───────────┤
│ 1   │ 0.006554 │ 0.049226 │ 0.126055 │ 0.293844 │ 0.600215 │ 0.00466   │
│ 2   │ 0.004671 │ 0.038688 │ 0.127381 │ 0.293281 │ 0.580099 │ 0.004762  │
│ 3   │ 0.004629 │ 0.037324 │ 0.126493 │ 0.307908 │ 0.640319 │ 0.004672  │
│ 4   │ 0.005143 │ 0.053126 │ 0.153393 │ 0.318974 │ 0.620704 │ 0.004839  │
│ 5   │ 0.010061 │ 0.061681 │ 0.194249 │ 0.4864   │ 0.998762 │ 0.006694  │
│ 6   │ 0.005622 │ 0.054245 │ 0.235787 │ 0.491879 │ 0.919742 │ 0.007219  │
│ 7   │ 0.004673 │ 0.03741  │ 0.124142 │ 0.295988 │ 0.583698 │ 0.004731  │
│ 8   │ 0.004689 │ 0.036951 │ 0.125586 │ 0.29707  │ 0.579931 │ 0.004749  │
│ 9   │ 0.004638 │ 0.037182 │ 0.125853 │ 0.295395 │ 0.574049 │ 0.004638  │
│ 10  │ 0.004696 │ 0.03706  │ 0.123495 │ 0.292471 │ 0.575187 │ 0.004717  │

In [40]:
data1 = [results[i][1] for i=1:5]
data2 = [results[i][2] for i=1:5]
data3 = [results[i][3] for i=1:5]
timestamps = [i for i=100:100:500]

5-element Array{Int64,1}:
 100
 200
 300
 400
 500

In [49]:
A1 =zeros(5, 4)
A1[:,1] = data1.^3
A1[:,2] = data1.^2
A1[:,3] = data1
A1[:,4] = ones(5)
A1F = factorize(A1)
res1 = A1F.R\((Transpose(A1F.Q)*timestamps)[1:4])
fit1 = polyfit(data1, timestamps, 3)
print(res1, fit1)

[88.1153, 2421.37, -6314.99, 5705.15]Poly(88.11530509090403 + 2421.3654122999733*x - 6314.986890379312*x^2 + 5705.150382905373*x^3)

In [50]:
A2 =zeros(5, 4)
A2[:,1] = data2.^3
A2[:,2] = data2.^2
A2[:,3] = data2
A2[:,4] = ones(5)
A2F = factorize(A2)
res2 = A2F.R\((Transpose(A2F.Q)*timestamps)[1:4])
fit2 = polyfit(data2, timestamps, 3)
print(res2, fit2)

[100.154, 2341.3, -6235.16, 5840.18]Poly(100.1537632708348 + 2341.2968946124383*x - 6235.157091318693*x^2 + 5840.180658242943*x^3)

In [51]:
A3 =zeros(5, 4)
A3[:,1] = data3.^3
A3[:,2] = data3.^2
A3[:,3] = data3
A3[:,4] = ones(5)
A3F = factorize(A3)
res3 = A3F.R\((Transpose(A3F.Q)*timestamps)[1:4])
fit3 = polyfit(data3, timestamps, 3)
print(res3, fit3)

[101.672, 2320.93, -6039.95, 5289.82]Poly(101.67180582772518 + 2320.929992553768*x - 6039.95290598552*x^2 + 5289.816890546481*x^3)